version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: yearly
    assignees:
      - aecomet
    labels:
      - dependabottest
    open-pull-requests-limit: 0
